# Generated by Django 4.0.2 on 2025-07-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_guild_description_alter_player_guild_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
